name: Deploy to SEOhost
on:
  push:
    branches: [ main ]  # lub master, zaleÅ¼nie od nazwy gÅ‚Ã³wnej gaÅ‚Ä™zi
  workflow_dispatch:    # pozwala na rÄ™czne uruchomienie

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ðŸ“‚ Checkout repository
      uses: actions/checkout@v3
    
    - name: ðŸ“¦ FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: h22.seohost.pl
        username: srv41873
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /domains/pnytko.pl/public_html/downview-2/
        dangerous-clean-slate: true
